export const ROLES = {
  CEO: 'CEO',
  GM: 'GM',
  FL: 'FL',
  FIN: 'FIN',
  TECH: 'TECH',
  INFO: 'INFO',
  IT: 'IT',
  HOT: 'HOT',
  ADMIN: 'ADMIN',
};

export const TENDER_STATUSES = {
  PENDING_FEASIBILITY: 'PENDING_FEASIBILITY',
  DOCUMENT_GATHERING: 'DOCUMENT_GATHERING',
  ASSEMBLY: 'ASSEMBLY',
  SUBMITTED: 'SUBMITTED',
  REJECTED: 'REJECTED',
};
